# Generated by Django 5.2.8 on 2026-10-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_contactmessage_assigned_to_internal_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="phone",
            field=models.CharField(blank=True, max_length=30, verbose_name="teléfono"),
        ),
    ]
