# Generated by Django 5.2.8 on 2026-10-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0003_contactmessage_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="kind",
            field=models.CharField(
                choices=[("CONTACT", "Contacto"), ("PRAYER", "Petición de oración")],
                db_index=True,
                default="CONTACT",
                max_length=10,
                verbose_name="tipo de solicitud",
            ),
        ),
    ]
